### PR TITLE
US946199: Use OpenSearch Image in tests

### PR DESCRIPTION
**Pull request by michael-bryson**
Ticket: https://internal.almoctane.com/ui/entity-navigation?p=131002/6001&entityType=work_item&id=946199

### CODE REVIEW

**Review by dermot-hardy — CHANGES_REQUESTED** [review]
I'd like to continue to test this against Elasticsearch.  Maybe we could add OpenSearch tests rather than replacing the ES ones?

**Comment by michael-bryson** [comment]
> I'd like to continue to test this against Elasticsearch. Maybe we could add OpenSearch tests rather than replacing the ES ones?

@dermot-hardy I think I have done this but the Jenkins test report only says 10 tests were executed but when I look in the logs it appears the tests are executed against both ES and OS. Is there something missing?

**Review by dermot-hardy — COMMENTED** [review]
I suspect your test summary files are overwriting each other.  Take a look at the CAF Storage Acceptance Tests.  It should have an example of running the tests multiple times in different modes and outputting separate reports to different locations.

**Comment by michael-bryson** [comment]
> I suspect your test summary files are overwriting each other. Take a look at the CAF Storage Acceptance Tests. It should have an example of running the tests multiple times in different modes and outputting separate reports to different locations.

Thanks, that should be it now.

**Review by dermot-hardy — APPROVED** [review]

**Pull request merged**
